site_name: Flux Documentation
site_description: Distributed workflow orchestration engine to build stateful and fault-tolerant workflows
repo_url: https://github.com/edurdias/flux
repo_name: edurdias/flux

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Light Mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Dark Mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/edurdias/flux
      name: Flux on GitHub

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: https://twemoji.maxcdn.com/v/latest/72x72/
      emoji_generator: pymdownx.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [flux]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Introduction:
    - Overview: introduction/overview.md
    - Key Features: introduction/features.md
    - Use Cases: introduction/use-cases.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Basic Concepts: getting-started/basic_concepts.md
    - Quick Start: getting-started/quick-start-guide.md
  - Core Concepts:
    - Workflows Management: user-guide/workflows-management.md
    - Tasks: user-guide/tasks.md
    - Error Handling: user-guide/error-handling.md
    - Execution Model: user-guide/execution-model.md
  - Advanced Features:
    - Task Patterns: advanced-features/task-patterns.md
    - Workflow Controls: advanced-features/workflow-controls.md
    # - Output Storage: advanced-features/output-storage.md
    # - Secrets Management: advanced-features/secrets-management.md
  # - Examples:
  #   - Basic Examples: examples/basic.md
  #   - Complex Workflows: examples/complex.md
  #   - Error Handling: examples/error-handling.md
  #   - Parallel Processing: examples/parallel.md
  # - API Reference:
  #   - Workflow: api/workflow.md
  #   - Task: api/task.md
  #   - Context: api/context.md
  #   - Events: api/events.md
  # - Contributing: contributing.md
